/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    services: Service;
    industries: Industry;
    'blog-posts': BlogPost;
    media: Media;
    testimonials: Testimonial;
    'team-members': TeamMember;
    'job-positions': JobPosition;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'job-positions': JobPositionsSelect<false> | JobPositionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'page-content': PageContent;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'page-content': PageContentSelect<false> | PageContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  layout?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            ctaText?: string | null;
            ctaLink?: string | null;
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            heading: string;
            description?: string | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            items?:
              | {
                  value: string;
                  label: string;
                  suffix?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richContent';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  category: 'core' | 'addon' | 'tool';
  order?: number | null;
  /**
   * Nome do ícone Lucide (ex: shield, heart, hard-hat)
   */
  icon?: string | null;
  /**
   * Frase curta abaixo do título no hero (ex: "Um software adaptado para...")
   */
  subtitle?: string | null;
  /**
   * Descrição curta para SEO e listagens
   */
  excerpt: string;
  /**
   * Descrição longa que aparece na página do módulo
   */
  descriptionText?: string | null;
  /**
   * URL da imagem hero (path relativo, ex: /images/modules/saude-trabalho-hero.jpg)
   */
  heroImageUrl?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Título da secção de funcionalidades
   */
  featuresHeading?: string | null;
  /**
   * Subtítulo da secção de funcionalidades
   */
  featuresSubheading?: string | null;
  features?:
    | {
        title: string;
        description?: string | null;
        /**
         * Nome do ícone Lucide
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  highlight?: {
    heading?: string | null;
    text?: string | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  title: string;
  slug: string;
  order?: number | null;
  /**
   * Nome do ícone Lucide (ex: factory, hard-hat, plane)
   */
  icon?: string | null;
  /**
   * Frase curta abaixo do título no hero
   */
  subtitle?: string | null;
  /**
   * Descrição curta para SEO e listagens
   */
  excerpt?: string | null;
  /**
   * Descrição longa que aparece na página do setor
   */
  descriptionText?: string | null;
  /**
   * URL da imagem hero (path relativo, ex: /images/modules/seguranca-trabalho-hero.jpg)
   */
  heroImageUrl?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Título da secção de funcionalidades
   */
  featuresHeading?: string | null;
  /**
   * Subtítulo da secção de funcionalidades
   */
  featuresSubheading?: string | null;
  features?:
    | {
        title: string;
        description?: string | null;
        /**
         * Nome do ícone Lucide
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  highlight?: {
    heading?: string | null;
    text?: string | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  relatedServices?: (number | Service)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: ('saude' | 'seguranca' | 'legislacao' | 'tecnologia' | 'novidades') | null;
  author?: (number | null) | TeamMember;
  publishedAt?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  photo?: (number | null) | Media;
  bio?: string | null;
  linkedin?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  clientName: string;
  clientRole?: string | null;
  company: string;
  quote: string;
  avatar?: (number | null) | Media;
  companyLogo?: (number | null) | Media;
  rating?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-positions".
 */
export interface JobPosition {
  id: number;
  title: string;
  department?: string | null;
  location?: string | null;
  type?: ('full-time' | 'part-time' | 'contract' | 'internship') | null;
  description?: string | null;
  responsibilities?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  active?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'job-positions';
        value: number | JobPosition;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              ctaText?: T;
              ctaLink?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    suffix?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richContent?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  order?: T;
  icon?: T;
  subtitle?: T;
  excerpt?: T;
  descriptionText?: T;
  heroImageUrl?: T;
  heroImage?: T;
  featuresHeading?: T;
  featuresSubheading?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  highlight?:
    | T
    | {
        heading?: T;
        text?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  icon?: T;
  subtitle?: T;
  excerpt?: T;
  descriptionText?: T;
  heroImageUrl?: T;
  heroImage?: T;
  featuresHeading?: T;
  featuresSubheading?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  highlight?:
    | T
    | {
        heading?: T;
        text?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  relatedServices?: T;
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  clientRole?: T;
  company?: T;
  quote?: T;
  avatar?: T;
  companyLogo?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  linkedin?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-positions_select".
 */
export interface JobPositionsSelect<T extends boolean = true> {
  title?: T;
  department?: T;
  location?: T;
  type?: T;
  description?: T;
  responsibilities?:
    | T
    | {
        text?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        text?: T;
        id?: T;
      };
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  logo?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  favicon?: (number | null) | Media;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  linkedin?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  /**
   * Ex: GTM-XXXXXXX
   */
  gtmId?: string | null;
  /**
   * Ex: G-XXXXXXXXXX
   */
  gaId?: string | null;
  /**
   * ID do portal HubSpot
   */
  hubspotId?: string | null;
  mivoEnabled?: boolean | null;
  mivoApiUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  mainNav?:
    | {
        label: string;
        link: string;
        children?:
          | {
              label: string;
              link: string;
              description?: string | null;
              icon?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaButton?: {
    label?: string | null;
    link?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-content".
 */
export interface PageContent {
  id: number;
  sobreHeroLabel?: string | null;
  sobreHeroTitle?: string | null;
  sobreHeroDescription?: string | null;
  sobreHeroImage?: (number | null) | Media;
  sobreMissionTitle?: string | null;
  sobreMissionText1?: string | null;
  sobreMissionText2?: string | null;
  sobreMissionImage?: (number | null) | Media;
  sobreStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  sobreValuesHeading?: string | null;
  sobreValues?:
    | {
        icon?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  sobreVersionsHeading?: string | null;
  sobreVersionsSubheading?: string | null;
  sobreVersions?:
    | {
        name: string;
        description?: string | null;
        features?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  sobreTeamTitle?: string | null;
  sobreTeamText1?: string | null;
  sobreTeamText2?: string | null;
  sobreTeamImage?: (number | null) | Media;
  sobreCtaTitle?: string | null;
  sobreCtaText?: string | null;
  carreirasHeroTitle?: string | null;
  carreirasHeroDescription?: string | null;
  carreirasHeroImage?: (number | null) | Media;
  carreirasCultureHeading?: string | null;
  carreirasCultureSubheading?: string | null;
  carreirasCultureValues?:
    | {
        icon?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  carreirasBenefitsTitle?: string | null;
  carreirasBenefitsImage?: (number | null) | Media;
  carreirasBenefits?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  carreirasPositionsHeading?: string | null;
  carreirasCtaTitle?: string | null;
  carreirasCtaText?: string | null;
  carreirasCtaEmail?: string | null;
  contactoHeroTitle?: string | null;
  contactoHeroDescription?: string | null;
  contactoPartnerName?: string | null;
  contactoPartnerDescription?: string | null;
  contactoPartnerWebsite?: string | null;
  contactoPartnerEmail?: string | null;
  contactoPartnerPhone?: string | null;
  contactoMapEmbed?: string | null;
  blogHeroTitle?: string | null;
  blogHeroDescription?: string | null;
  blogCtaTitle?: string | null;
  blogCtaText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  logoDark?: T;
  favicon?: T;
  email?: T;
  phone?: T;
  address?: T;
  linkedin?: T;
  facebook?: T;
  instagram?: T;
  youtube?: T;
  gtmId?: T;
  gaId?: T;
  hubspotId?: T;
  mivoEnabled?: T;
  mivoApiUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        link?: T;
        children?:
          | T
          | {
              label?: T;
              link?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
        id?: T;
      };
  ctaButton?:
    | T
    | {
        label?: T;
        link?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-content_select".
 */
export interface PageContentSelect<T extends boolean = true> {
  sobreHeroLabel?: T;
  sobreHeroTitle?: T;
  sobreHeroDescription?: T;
  sobreHeroImage?: T;
  sobreMissionTitle?: T;
  sobreMissionText1?: T;
  sobreMissionText2?: T;
  sobreMissionImage?: T;
  sobreStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  sobreValuesHeading?: T;
  sobreValues?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  sobreVersionsHeading?: T;
  sobreVersionsSubheading?: T;
  sobreVersions?:
    | T
    | {
        name?: T;
        description?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        highlight?: T;
        id?: T;
      };
  sobreTeamTitle?: T;
  sobreTeamText1?: T;
  sobreTeamText2?: T;
  sobreTeamImage?: T;
  sobreCtaTitle?: T;
  sobreCtaText?: T;
  carreirasHeroTitle?: T;
  carreirasHeroDescription?: T;
  carreirasHeroImage?: T;
  carreirasCultureHeading?: T;
  carreirasCultureSubheading?: T;
  carreirasCultureValues?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  carreirasBenefitsTitle?: T;
  carreirasBenefitsImage?: T;
  carreirasBenefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  carreirasPositionsHeading?: T;
  carreirasCtaTitle?: T;
  carreirasCtaText?: T;
  carreirasCtaEmail?: T;
  contactoHeroTitle?: T;
  contactoHeroDescription?: T;
  contactoPartnerName?: T;
  contactoPartnerDescription?: T;
  contactoPartnerWebsite?: T;
  contactoPartnerEmail?: T;
  contactoPartnerPhone?: T;
  contactoMapEmbed?: T;
  blogHeroTitle?: T;
  blogHeroDescription?: T;
  blogCtaTitle?: T;
  blogCtaText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}